Del3 - Copy/INF272_Project/INF272_Project/Models/Question.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionID { get; set; }
        public int SubjectID { get; set; }
        public string Question1 { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Subject Subject { get; set; }
    }
}

Del3 - Copy/INF272_Project/INF272_Project/ViewModels/QuestionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace INF272_Project.ViewModels
{
    public class QuestionViewModel
    {
        public int QuestionID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public double MarkAllocation { get; set; }


        public List<QuestionViewModel> QuestionsList { get; set; }
        public List<QuestionViewModel> Questions { get; set; }

        public QuestionViewModel()
        {
            QuestionID = 0;
            Description = "";
            MarkAllocation = 0;
            Subject = "";

        }


        public QuestionViewModel(int ID, string description, int markAllocation, string subject)
        {
            QuestionID = ID;
            Description = description;
            MarkAllocation = markAllocation;
            Subject = subject;


        }
    }
}

Del3 - Copy/INF272_Project/INF272_Project/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using INF272_Project.ViewModels;

namespace INF272_Project.Controllers
{
    public class QuestionController : Controller
    {
        public List<QuestionViewModel> Questions = new List<QuestionViewModel>();
        // GET: Question
        public ActionResult Index()
        {
           
            return View(Questions);
        }

        // GET: Question/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Question/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Question/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Question/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Question/Edit/5
        [HttpPost]
        public ActionResult Edit(/*int id, FormCollection collection*/)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Question/Delete/5
        public ActionResult Delete(/*int id*/)
        {
            return View();
        }

        // POST: Question/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Del3 - Copy/INF272_Project/INF272_Project/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using INF272_Project.Models;

namespace INF272_Project.Controllers
{
    public class QuestionsController : Controller
    {
        private StarKidzEntities1 db = new StarKidzEntities1();

        // GET: Questions
        public ActionResult Index()
        {
            var questions = db.Questions.Include(q => q.Grade).Include(q => q.Subject);
            return View(questions.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            ViewBag.GradeID = new SelectList(db.Grades, "GradeID", "Description");
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "Title");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QuestionID,SubjectID,Question1,Answer,GradeID,Marks")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GradeID = new SelectList(db.Grades, "GradeID", "Description", question.GradeID);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "Title", question.SubjectID);
            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.GradeID = new SelectList(db.Grades, "GradeID", "Description", question.GradeID);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "Title", question.SubjectID);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "QuestionID,SubjectID,Question1,Answer,GradeID,Marks")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GradeID = new SelectList(db.Grades, "GradeID", "Description", question.GradeID);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "Title", question.SubjectID);
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Del3 - Copy/INF272_Project/INF272_Project/Views/Question/Create.cshtml
@model INF272_Project.ViewModels.QuestionViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Question</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarkAllocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarkAllocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarkAllocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Index")
</div>

<style>
    body {
        background-image: url('../../Content/moving-stars-on-black-background_41x3vg3x__F0000.png');
        background-size: cover;
        background-repeat: no-repeat;
        color: white;
    }
</style>

Del3 - Copy/INF272_Project/INF272_Project/Views/Question/Delete.cshtml
@model INF272_Project.ViewModels.QuestionViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete Question</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuestionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuestionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarkAllocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarkAllocation)
        </dd>

    </dl>

    @using (Html.BeginForm("Index", "Question")) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back", "Index")
        </div>
    }
</div>

<style>
    body {
        background-image: url('../../Content/moving-stars-on-black-background_41x3vg3x__F0000.png');
        background-size: cover;
        background-repeat: no-repeat;
        color: white;
    }
</style>

Del3 - Copy/INF272_Project/INF272_Project/Views/Question/Edit.cshtml
@model INF272_Project.ViewModels.QuestionViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit This Question</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>QuestionViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QuestionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarkAllocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarkAllocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarkAllocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Del3 - Copy/INF272_Project/INF272_Project/Views/Question/Index.cshtml
@model IEnumerable<INF272_Project.ViewModels.QuestionViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        background-image: url('../../Content/21074350-modern-white-background-seamless-patterns.jpg');
    }

    h1 {
        color: midnightblue;
        text-align: left;
        font-family: 'Comic Sans MS'
    }

    h2 {
        color: midnightblue;
        text-align: left;
        font-family: 'Comic Sans MS';
    }

    label {
        color: midnightblue;
        font-family: Calibri;
    }

    p {
        font-size: 20px;
        font-family: Calibri;
        color: midnightblue;
    }

    table {
        width: 70%;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    th {
        background-color: midnightblue;
        font-family: 'Comic Sans MS';
        color: white;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<h2>Questions</h2>

<p>
    @Html.ActionLink("Add Question", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.QuestionID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MarkAllocation)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MarkAllocation)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

</table>

<p>
    @Html.ActionLink("Delete Question", "Delete")
</p>
<br />
<br />
<input type="submit" value="Back" onclick="@("window.location.href='" + @Url.Action("adminHome", "Star") + "'");" style="color:black">

<style>
    body {
        background-image: url('../../Content/933808-school-backgrounds-1920x1200-images.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        color: white;
    }
</style>