Del3/INF272_Project/INF272_Project/Models/Homework.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public int HomeworkID { get; set; }
        public int LearnerID { get; set; }
        public System.DateTime HomeworkDate { get; set; }
        public string Description { get; set; }
    
        public virtual Learner Learner { get; set; }
    }
}

Del3/INF272_Project/INF272_Project/Controllers/HomeworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using INF272_Project.ViewModels;
using INF272_Project.Models;

namespace INF272_Project.Controllers
{

    public class HomeworkController : Controller
    {      public List<QuestionViewModel> Questions = new List<QuestionViewModel>();
        StarKidzEntities1 db = new StarKidzEntities1();
        // GET: Homework
        public ActionResult UserHW()
        {
       

            int grade = 5;
           
            List<Question> question = db.Questions.Where(kk => kk.GradeID == grade).ToList();


            for (var k = 0; k < 5; k++)
            {
                Random random = new Random();
                k = random.Next(1, question.Count());

                Question q = question[k];

                var a = db.Subjects.Where(b => b.SubjectID == q.SubjectID).FirstOrDefault();
                QuestionViewModel obj = new QuestionViewModel(question[k].QuestionID,
                                                               a.Title,
                                                               question[k].Question1,
                                                               question[k].Answer.GetValueOrDefault(),
                                                               question[k].GradeID.GetValueOrDefault(),
                                                               question[k].Marks.GetValueOrDefault()
                                                               );
                Questions.Add(obj);
            }
            return View(Questions);

        
         

        }
        public ActionResult UserHWResults(int id)
        {
            Homework homework = new Homework();
            homework.Description = "homework" + ((db.Homeworks.Where(ff => ff.LearnerID == 1).ToList()).Count());
            homework.LearnerID = id;
            homework.HomeworkDate = DateTime.Today;
            db.SaveChanges();
            return View();
        }
    }
}

Del3/INF272_Project/INF272_Project/Views/Homework/UserHW.cshtml
@model List<INF272_Project.ViewModels.QuestionViewModel>
@{
    ViewBag.Title = "UserHW";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Homework</h2>



<style>
    body {
        background-image: url('../../Content/21074350-modern-white-background-seamless-patterns.jpg');
    }

    h1 {
        color: midnightblue;
        text-align: left;
        font-family: 'Comic Sans MS'
    }

    h2 {
        color: midnightblue;
        text-align: left;
        font-family: 'Comic Sans MS';
    }

    label {
        color: midnightblue;
        font-family: Calibri;
    }

    p {
        font-size: 20px;
        font-family: Calibri;
        color: midnightblue;
    }

    table {
        width: 70%;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    th {
        background-color: midnightblue;
        font-family: 'Comic Sans MS';
        color: white;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>


<h1>STAR kidZ</h1>
<h2>Homework</h2>
<div>
    <table>
        <tr>
            <th>Subject</th>
            <th>Question</th>
            <th>Max Marks</th>
            <th>Answer</th>
        </tr>
        <tr>
            @{ List<int> Ids = new List<int>();

                foreach (var item in Model)
                {
                <tr>

                    <td>@item.Subject</td>
                    <td>@item.Question</td>
                    <td>@item.Marks</td>
                    <td><input type="text" value="" name=@item.QuestionID></td>
                </tr>
                Ids.Add(item.QuestionID);
            }
            }




        </table>
        <br />
    </div>

    @using (Html.BeginForm("UserHWResults", "Homework"))
    {
        <label>LearnerID:</label>
        <input type="text"value="" name="id"/>
        <input type="submit" value="Submit homework" />
    }

Del3/INF272_Project/INF272_Project/Views/Homework/UserHWResults.cshtml
@model List<INF272_Project.ViewModels.QuestionViewModel>
@{
    ViewBag.Title = "UserHWResults";
}
<style>
    body {
        background-image: url('../../Content/21074350-modern-white-background-seamless-patterns.jpg');
    }

    h1 {
        color: midnightblue;
        text-align: left;
        font-family: 'Comic Sans MS'
    }

    h2 {
        color: midnightblue;
        text-align: left;
        font-family: 'Comic Sans MS';
        align-content: center;
    }

    label {
        color: midnightblue;
        font-family: Calibri;
        font-size: 20px;
        align-content: center;
    }

    p {
        font-size: 20px;
        font-family: Calibri;
        color: midnightblue;
    }

    table {
        width: 70%;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    th {
        background-color: midnightblue;
        font-family: 'Comic Sans MS';
        color: white;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<h1>STAR kidZ</h1>
<h2>The correct answers are: </h2>
<div>
    <table>
        <tr>
            <th>Question</th>
            <th>Max Marks</th>
            <th>Answer</th>
            <th>Your Score</th>
        </tr>
        <tr>



            <th>Subject</th>
            <th>Question</th>
            <th>Max Marks</th>
            <th>Correct Answer</th>
        </tr>
        <tr>
            @{
                foreach (var item in Model)
                {


                    <td>@item.Subject</td>
                    <td>@item.Question</td>
                    <td>@item.Marks</td>

                    <td>@item.Answer</td>

                }

            </tr>

        </table>
    </div>
    <input onclick="@("window.location.href='" + @Url.Action("home", "Star") + "'");" type="submit" value="Back to homepage" />